### PR TITLE
Added Station.all

### PR DESCRIPTION
**Pull request by dkniffin**
Now, we can do `NDBC::Station.all`, and it will return an array of `NDBC::Station`s. This is handy for DB imports and such.

### CODE REVIEW

**Comment by ryanhertz** [comment]
Looks great, thanks!

**Comment by dkniffin** [comment]
Awesome. That's all the changes I have for now. I'll probably find some more at some point. Mind pushing out a new version of the gem?

**Comment by ryanhertz** [comment]
Done. https://rubygems.org/gems/ndbc

**Comment by dkniffin** [comment]
Thanks!

**Pull request merged**
